server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
            - config
          default-label: master
          username: 139199502@qq.com
          password: fyz199526

