server:
  port: 9000

spring:
  application:
    name: provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.159.128:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: payment1
server:
  port: 9001
---
spring:
  profiles: payment2
server:
  port: 9002

