# 单节点模式
spring:
  application:
    name: eureka-server

server:
  port: 7000

eureka:
  instance:
    # 实例主机名
    hostname: localhost
  client:
    # 不注册到Eureka
    fetch-registry: false
    # 不获取注册中心
    register-with-eureka: false
    service-url:
      # Eureka Server地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 删除无效节点间隔时间
    eviction-interval-timer-in-ms: 2000

---
# 集群模式-节点1
spring:
  application:
    name: eureka-server
  profiles: eureka1
server:
  port: 7001
eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
---
# 集群模式-节点2
spring:
  application:
    name: eureka-server
  profiles: eureka2
server:
  port: 7002
eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka3:7003/eureka/
---
# 集群模式-节点3
spring:
  application:
    name: eureka-server
  profiles: eureka3
server:
  port: 7003
eureka:
  instance:
    hostname: eureka3
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/